name: Markdown Check

on:
  pull_request:
    paths:
      - '**/*.md'
      - '.github/workflows/markdown-check.yml'

jobs:
  markdown-check:
    name: Check Markdown files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check Links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress '**/*.md'
          jobSummary: false
          fail: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for typos
        uses: crate-ci/typos@master
        with:
          files: ./**/*.md

      - name: Run markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: |
            **/*.md
            #lychee/out.md
          config: '.github/config/custom.markdownlint.yml'
